#!/bin/bash
#SBATCH -J ML-BOP
#SBATCH -o out.o%j
#SBATCH -e out.e%j
#SBATCH -t 5-2:57:33
#SBATCH -B 2:12:1
#SBATCH --mem-per-cpu=2G
#SBATCH --cpus-per-task=1
#SBATCH -n 2 -N 1


# --------------------------------- Command Line Options --------------------------------
# -c (cores) "number of cores assigned"
# -j (jobid) "slurm jobid"
# -m (mode)  "debug" or "run" (Optional) 
# -i (input) "A string: input file name" 
# -Ref (reference data address) (Optional) 
# -prep (template folder for running sampling method) (Optional)

# $SLUMR_NTASKS: Number of cores requested from SBATCH -n 
# $SLUMR_JOBID: JOB ID assigned after submitting the job 


optimize -c $SLURM_NTASKS -j force_mathcing_$SLURM_JOBID -i in_obj -Ref ../../ReferenceData -prep ../../prepsystem 
