#!/bin/bash 

conda  activate optimize 

module load intel/psxe-2019-64-bit

f2py -c readtraj.f90 -m reader --fcompiler=intelem --compiler=unix

f2py -c compute_rdf.f90 -m computerdf --fcompiler=intelem --compiler=unix 

