#!/bin/bash
#SBATCH -J ML_mW
#SBATCH -o ML_mW.out 
#SBATCH -e ML_mW.err
#SBATCH -t 1-10:57:33
#SBATCH -n 8 -N 1 
#SBATCH -p palmer

module load intel/psxe-2019-64-bit

mpirun lmp_ml_water < in.isobar

